# Generated by Django 5.2.6 on 2025-09-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history_attendance',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
