# Generated by Django 5.2.6 on 2025-09-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_history_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
