# Generated by Django 5.2.6 on 2025-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_students_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mssv',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
